export const languages = [
    { code: 'es', label: 'Español' },
    { code: 'en', label: 'English' },
    { code: 'ar', label: 'عربى' },
    { code: 'an', label: 'Aragonés' },
    { code: 'bg', label: 'български' },
    { code: 'br', label: 'Português do Brasil' },
    { code: 'ca', label: 'Català' },
    { code: 'cs', label: 'Čeština' },
    { code: 'de', label: 'Deutsche' },
    { code: 'et', label: 'Eestlane' },
    { code: 'eu', label: 'Euskal' },
    { code: 'fa', label: 'فارسی' },
    { code: 'fr', label: 'Français' },
    { code: 'gl', label: 'Galego' },
    { code: 'he', label: 'עברי' },
    { code: 'hr', label: 'Hrvatski' },
    { code: 'hu', label: 'Magyar' },
    { code: 'it', label: 'Italiano' },
    { code: 'ko', label: '한국어' },
    { code: 'lt', label: 'Lietuvių' },
    { code: 'lv', label: 'Latviski' },
    { code: 'mk', label: 'Македонски' },
    { code: 'el', label: 'Ελληνικά' },
    { code: 'nb', label: 'Norsk' },
    { code: 'nl', label: 'Nederlands' },
    { code: 'pl', label: 'Polski' },
    { code: 'pt', label: 'Português' },
    { code: 'ro', label: 'Română' },
    { code: 'ru', label: 'Pусский' },
    { code: 'sk', label: 'Slovenský' },
    { code: 'sl', label: 'Slovenščina' },
    { code: 'sq', label: 'Shqip' },
    { code: 'sv', label: 'Svenska' },
    { code: 'sr', label: 'Српски' },
    { code: 'uk', label: 'Yкраїнська' },
    { code: 'val', label: 'Valencia' },
    { code: 'zh', label: '简体中文）' },
];

export default languages;
